name: Build LaTeX Report PDF
on:
  workflow_dispatch:
  push:
    paths:
      - "reports/main.tex"
      - ".github/workflows/build-report.yml"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install required fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-firacode
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: reports/
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          continue_on_error: true
          extra_fonts: |
            /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
            /usr/share/fonts/truetype/firacode/FiraCode-Regular.ttf
          extra_system_packages: "fonts-firacode"
      - name: Commit and push PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add reports/main.pdf
          git commit -m "Update report PDF" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: research-paper
          path: reports/main.pdf
          if-no-files-found: error
